### ISSUE TITLE
comparePdfToSnapshot returns false when files are visually the same but size is different

### ISSUE THREAD

**Issue by AntonioLok** [moshensky/pdf-visual-diff#47]
Hello,

I finally was able to get it working on my docker container. I saved an initial snapshot and now I am comparing it against a new pdf (same content visually) but the size is a bit different. I should expect comparePdfToSnapshot  to return true but its returning false. is this expected? If so, is there a way to only compare it visually?

I have attached old and new pdf generated as well as the .diff file. I compared it manually and also through https://www.diffchecker.com/image-diff/. 

![expectedTile2PDFBuffer new](https://user-images.githubusercontent.com/14690224/173635421-4774d522-7445-47ff-aced-73ec46292948.png)
![expectedTile2PDFBuffer diff](https://user-images.githubusercontent.com/14690224/173635424-040e4acf-2089-4834-a93f-692ce059181b.png)
![expectedTile2PDFBuffer](https://user-images.githubusercontent.com/14690224/173635413-349d90ea-af40-4b14-b99a-38e406d4b447.png)

**Comment by moshensky** [comment]
Hi @AntonioLok,

I've run your new and orig images via v0.6.0 comparison function and got a bit different [diff](https://ibb.co/2ycXkRp).
It is clear that there are changes in the images and probably fonts.
What I would have done is to check if the new image would compare successfully, i.e. rename the new image as orig and run test again.

P.S. Could you please edit your post so that image links won't be embedded for easier readability please?
