### ISSUE TITLE
Trouble with masking coordinates

### ISSUE THREAD

**Issue by GrayedFox** [moshensky/pdf-visual-diff#63]
Hello there and thank you for this epic tool, I'm phasing out the old way our company handles PDF comparison and adopting this for all of our automation moving forward (solid choice on all proj dependencies too, made the dev-sec review process a breeze!).

I'm having a bit of trouble figuring out the appropriate coordinates for my masks. This is likely a bit off topic as it's a math question and not really related to the library but I thought the discussion may prove useful for future eyeballs, once we get to the bottom of it I'm happy to open a PR that updates the readme or adds a wiki/doc page as appropriate :)

I assumed that the coordinate system uses the same origin as the PDF spec (i.e. `0,0` bottom-left origin), but when I apply a mask to a PDF using a bottom-left based **points** coordinate it ends up far from where it should be.

I then considered that it could be that the mask coordinate system used by Jimp assumes a top-left origin but then I should have seen the mask appear in the correct horizontal position and it was off on both the X and Y axis.

Then I realised it might be that the coordinates for each page need to be given in pixels if the mask is being applied after it's converted to a PNG (which [I think it is][0]) so I factored in my monitors DPI in an attempt to translate the coords.

I have two different displays each with different DPIs, the below formula resulted in the mask being moved either too far or not quite enough towards the target.

```js
// DPI value either 192 or 96 depending on which monitor it's running on
mask.y = Math.round((mask.y * cypressEnv.MONITOR_DPI) / 72);
mask.x = Math.round((mask.x * cypressEnv.MONITOR_DPI) / 72);
```

I'm running these specs in Cypress (migration to PlayWright will be happening in the future) and the viewport of the test runner in Cypress is `1280x800`. Eventually I landed on these values, which applied the mask appropriately:

```js
// options should contain pdf buffer, local pdf path, local pdf name, and optional masks
comparePdfs(options) {
    const { buffer, path, name, masks } = options;
    return comparePdfToSnapshot(Buffer.from(buffer), path, name, {
        // this callback is exceuted per page of the pdf during the diff, if we have a matching mask then apply it
        maskRegions: page => {
            /** @type {import('pdf-visual-diff/lib/compare-pdf-to-snapshot').RegionMask} */
            const mask = masks?.find(mask => mask.page === page);
            if (mask) {
                // standard PDF page dimensions at 72 PPI is 595w 842h, coordinates to pixels formula must factor in monitor PPI, grab it quickly with https://www.infobyip.com/detectmonitordpi.php
                // mask.y = 842 - mask.y; // invert y coordinate, not needed
                const pointsToPixles = point => Math.round((point * 144) / 72);
                mask.y = pointsToPixles(mask.y);
                mask.x = pointsToPixles(mask.x);
                mask.height = pointsToPixles(mask.height);
                mask.width = pointsToPixles(mask.width);
                console.log(`MASK ${JSON.stringify(mask)}`);
                return [mask];
            }
        }
    });
}
```

This applies the mask in the right location and also increases the size of the mask to the expected size - but I don't quite get why. Like, what is the relationship of the number 144 to the viewport? This equation applies the mask correctly on both my monitors which are very different (super widescreen with 96 DPI at 39", native Macbook 14" at 192 DPI) - is there anyone here that can help this vector math rookie shed some light?

Thanks internet 🧠 

Edit: may be relevant I am just using Preview to get the coords, see pic

![image](https://github.com/user-attachments/assets/3ac83842-78ba-48a4-bed8-5fda34867902)

[0]: https://github.com/moshensky/pdf-visual-diff/blob/master/src/compare-pdf-to-snapshot.ts#L32

**Comment by moshensky** [comment]
👋 @GrayedFox,

Masking is applied at the PNG level, i.e., after the conversion of the PDF to an image. Therefore, the values provided for `x`, `y`, `width`, and `height` are expected to be in pixels and based on the generated image by the library. The origin (0,0) of the PNG's coordinate system is the top-left corner of the image. Since PNG is a raster format, the monitor's DPI doesn't affect coordinate determination as long as the tool used for measurement references the image's pixels.

This library uses [PDF.js](https://mozilla.github.io/pdf.js/) to convert PDFs to PNGs. When rendering, each PDF page has its own viewport, defining the pixel size at 72 DPI. By default, the viewport is scaled to the PDF's original size, but we modify it by doubling the viewport's scale (inside [getPageViewPort](https://github.com/moshensky/pdf-visual-diff/blob/23a9742a0dd346d33687f4b0caf8382fe099dfae/src/pdf2png.ts#L79) function). As a result, PNGs are generated at **144 DPI** by default, meaning the generated image size in pixels is twice the size of the PDF page in points.
For example, a PDF with dimensions of **595×842** points (A4 page size) would correspond to:
- Width of `595 / 72 = 8.3` inches
- Height of `842 / 72 = 11.7` inches

When rendering or printing a PDF of this size, DPI becomes crucial:

|  At DPI | Size in pixels |
| ------: | :------------: |
|  **72** |  **595x841**   |
|      96 |    793x1123    |
| **144** | **1190x1684**  |
|     192 |   1587x2245    |
| 300 |   2480x3508    |

This means that 144 DPI has a straightforward relationship when calculating pixel coordinates from PDF points, as you noted `points * 144 / 72` simply reduces to `points * 2` in this specific case.

I have a [PR](https://github.com/moshensky/pdf-visual-diff/pull/64) that introduces an option to disable scaling, which offers the added benefit of much faster comparisons at the cost of the image quality. However, when scaling is disabled, PDF points would essentially correspond directly to pixels, so you wouldn't need to multiply by 2 when defining masks. An alternative could be to add an option to define masks in points. Should we then base the masking on the PDF origin (0,0), which is located at the bottom-left corner?

**Comment by GrayedFox** [comment]
Ahoy there and thanks for the detailed breakdown and explanation - I kept thinking about the viewport in Cypress and didn't see that 144 / 72 is actually just 2 - that was the ticket 💯
